const countries = {
    "am-ET": "Amharic",
    "ar-SA": "Arabic",
    "bn-BD": "Bengali",
    "cs-CZ": "Czech",
    "da-DK": "Danish",
    "de-DE": "German",
    "el-GR": "Greek",
    "en-US": "English",
    "es-ES": "Spanish",
    "fa-IR": "Persian",
    "fi-FI": "Finnish",
    "fr-FR": "French",
    "he-IL": "Hebrew",
    "hi-IN": "Hindi",
    "hu-HU": "Hungarian",
    "id-ID": "Indonesian",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "ko-KR": "Korean",
    "ms-MY": "Malay",
    "nl-NL": "Dutch",
    "no-NO": "Norwegian",
    "pl-PL": "Polish",
    "pt-BR": "Portuguese",
    "ro-RO": "Romanian",
    "ru-RU": "Russian",
    "sv-SE": "Swedish",
    "ta-IN": "Tamil",
    "th-TH": "Thai",
    "tr-TR": "Turkish",
    "uk-UA": "Ukrainian",
    "vi-VN": "Vietnamese",
    "zh-CN": "Chinese (Simplified)",
    "zh-TW": "Chinese (Traditional)"
};